import { Book, QuizQuestion, LeaderboardUser, Badge, VocabularyWord } from './types';
import { STORIES_PART1, RawStory } from './stories_part1';
import { STORIES_PART2 } from './stories_part2';
import { AVATAR_OPTIONS } from './avatar_assets';
import { STORY_TITLE_TRANSLATIONS } from './story_title_translations';


// Combined 50 famous stories catalog
export const ALL_RAW_STORIES: RawStory[] = [...STORIES_PART1, ...STORIES_PART2];

// Level descriptions
const LEVEL_NAMES: { [key: string]: string } = {
  A1: 'A1 Başlangıç / Beginner',
  A2: 'A2 Temel / Elementary',
  B1: 'B1 Orta / Intermediate',
  B2: 'B2 İleri Orta / Upper Intermediate',
  C1: 'C1 İleri / Advanced'
};

// Global dictionary with high-frequency fairy tale/famous story words for automated lookup fallbacks!
export const GLOBAL_DICTIONARY: { [key: string]: string } = {
  "hello": "merhaba",
  "hi": "selam",
  "ok": "tamam",
  // Original entries
  "once": "bir zamanlar",
  "upon": "üzerine",
  "time": "zaman/vakit",
  "little": "küçük/ufak",
  "girl": "kız",
  "lived": "yaşadı",
  "near": "yakınında",
  "forest": "orman",
  "she": "o (kadın)",
  "he": "o (erkek)",
  "they": "onlar",
  "we": "biz",
  "you": "sen/siz",
  "wore": "giydi",
  "beautiful": "güzel",
  "knew": "biliyordu",
  "mother": "anne",
  "said": "dedi",
  "please": "lütfen",
  "take": "almak/götürmek",
  "basket": "sepet",
  "sweet": "tatlı",
  "apples": "elmalar",
  "grandmother": "büyükanne",
  "but": "ama/fakat",
  "talk": "konuşmak",
  "to": "e/a yönelme",
  "any": "hiçbir/herhangi bir",
  "on": "üzerinde",
  "kind": "nazik/tür",
  "bad": "kötü",
  "two": "iki",
  "made": "yaptı/zorladı",
  "her": "onu/ona",
  "do": "yapmak",
  "all": "hepsi/tüm",
  "hard": "zor/sıkı",
  "house": "ev",
  "there": "orada/var",
  "was": "idi/vardı",
  "princess": "prenses",
  "with": "ile",
  "dark": "karanlık/koyu",
  "hair": "saç",
  "white": "beyaz",
  "skin": "ten/cilt",
  "very": "çok",
  "asked": "sordu/istedi",
  "go": "gitmek",
  "found": "buldu",
  "small": "küçük",
  "seven": "yedi",
  "family": "aile",
  "poor": "fakir",
  "had": "sahipti/vardı",
  "no": "yok/hayır",
  "food": "yiyecek/yemek",
  "night": "gece",
  "walked": "yürüdü",
  "soon": "kısa süre sonra",
  "saw": "gördü",
  "young": "genç",
  "boy": "erkek çocuk",
  "only": "sadece",
  "one": "bir",
  "sold": "sattı",
  "magic": "sihirli",
  "during": "esnasında",
  "grew": "büyüdü",
  "plant": "bitki/fidan",
  "clouds": "bulutlar",
  "three": "üç",
  "wanted": "istedi",
  "build": "inşa etmek",
  "first": "birinci",
  "built": "inşa etti",
  "because": "çünkü",
  "quick": "hızlı/seri",
  "second": "ikinci",
  "third": "üçüncü",
  "strong": "güçlü",
  "stay": "kalmak",
  "sat": "oturdu",
  "eggs": "yumurtalar",
  "big": "büyük",
  "baby": "bebek",
  "bird": "kuş",
  "large": "iri/geniş",
  "other": "diğer",
  "animals": "hayvanlar",
  "day": "gün",
  "long": "uzun",
  "empty": "boş",
  "inside": "içeride",
  "bowls": "kaseler",
  "warm": "ılık/sıcak",
  "table": "masa",
  "came": "geldi",
  "incredibly": "inanılmaz derecede",
  "old": "yaşlı",
  "high": "yüksek",
  "doors": "kapılar",
  "room": "oda",
  "let": "izin vermek/salmak",
  "wooden": "ahşap/tahtadan",
  "real": "gerçek",
  "if": "eğer",
  "loved": "sevdi/seviyordu",
  "reading": "okuma/okumak",
  "books": "kitaplar",
  "save": "kurtarmak/kaydetmek",
  "slowly": "yavaşça",
  "discovered": "keşfetti",
  "heart": "kalp",
  "fell": "düştü/kapıldı",
  "love": "aşk/sevgi",
  "born": "doğdu",
  "finger": "parmak",
  "die": "ölmek",
  "another": "diğer/başka bir",
  "changed": "değiştirdi",
  "hundred": "yüz",
  "years": "yıllar",
  "mermaid": "denizkızı",
  "blue": "mavi",
  "dreamed": "hayal etti",
  "wonderful": "harika/muhteşem",
  "world": "dünya",
  "above": "üzerinde",
  "water": "su",
  "handsome": "yakışıklı",
  "sinking": "batan",
  "wished": "diledi/istedi",
  "man": "adam",
  "busy": "meşgul/kalabalık",
  "genie": "cin",
  "appeared": "belirdi",
  "wishes": "dilekler",
  "running": "koşu/koşan",
  "tree": "ağaç",
  "never": "asla",
  "marry": "evlenmek",
  "wet": "ıslak",
  "woman": "kadın",
  "knocked": "çaldı",
  "gates": "kapılar/şehir kapıları",
  "tested": "test etti/denedi",
  "thick": "kalın",
  "flower": "çiçek",
  "adventures": "maceralar",
  "neverland": "olmayan ülke",
  "lost": "kayıp",
  "exciting": "heyecan verici",
  "against": "karşı",
  "merry": "neşeli/şifalı",
  "fought": "savaştı",
  "rich": "zengin",
  "grass": "çimen",
  "rabbit": "tavşan",
  "smart": "şık/zeki",
  "deep": "derin",
  "hole": "delik",
  "filled": "dolu",
  "bored": "sıkılmış",
  "flock": "sürü",
  "sheep": "koyunlar",
  "mountain": "dağ",
  "times": "kez/seferler",
  "laughing": "gülüyor/gülmek",
  "hungry": "aç",
  "purple": "mor",
  "hanging": "sarkan/asılan",
  "strength": "güç/kuvvet",
  "jumped": "zıpladı",
  "continually": "sürekli",
  "reach": "ulaşmak",
  "hardworking": "çalışkan",
  "gold": "altın",
  "cave": "mağara",
  "words": "kelimeler/sözler",
  "seas": "denizler",
  "island": "ada",
  "suddenly": "aniden",
  "back": "sırt/arka",
  "shiny": "parlak",
  "rose": "gül",
  "garden": "bahçe",
  "textbooks": "ders kitapları",
  "corridor": "koridor",

  // Critical missing words
  "road": "yol/cadde",
  "path": "patika/yol",
  "street": "sokak/cadde",
  "bridge": "köprü",
  "village": "köy",
  "town": "kasaba",
  "city": "şehir",
  "castle": "kale/şato",
  "palace": "saray",
  "tower": "kule",
  "temple": "tapınak",
  "church": "kilise",
  "market": "pazar/çarşı",
  "shop": "dükkan/mağaza",
  "inn": "han/pansiyon",
  "farm": "çiftlik",
  "barn": "ahır/ambar",
  "stable": "ahır/istikrarlı",
  "river": "nehir/ırmak",
  "lake": "göl",
  "sea": "deniz",
  "ocean": "okyanus",
  "pond": "gölet",
  "stream": "dere/akarsu",
  "hill": "tepe",
  "valley": "vadi",
  "plain": "ova/düz",
  "desert": "çöl",
  "jungle": "orman/cengel",
  "sky": "gökyüzü",
  "star": "yıldız",
  "moon": "ay",
  "sun": "güneş",
  "cloud": "bulut",
  "rain": "yağmur",
  "snow": "kar",
  "wind": "rüzgar",
  "storm": "fırtına",
  "thunder": "gök gürültüsü",
  "lightning": "şimşek",
  "fire": "ateş",
  "smoke": "duman",
  "flame": "alev",
  "ash": "kül",
  "ice": "buz",
  "earth": "toprak/yer/dünya",
  "land": "arazi/ülke",
  "ground": "zemin/yer",
  "soil": "toprak",
  "mud": "çamur",
  "dust": "toz",
  "air": "hava",
  "stone": "taş",
  "rock": "kaya",
  "sand": "kum",
  "door": "kapı",
  "window": "pencere",
  "wall": "duvar",
  "floor": "zemin/kat",
  "ceiling": "tavan",
  "roof": "çatı",
  "gate": "kapı/bahçe kapısı",
  "trail": "iz/patika",
  "track": "iz/pist/takip etmek",
  "field": "tarla/alan",
  "yard": "avlu/bahçe",
  "pool": "havuz/gölet",
  "well": "kuyu/iyi",
  "breath": "nefes",
  "voice": "ses/konuşma",
  "sound": "ses/sesi çıkmak",
  "noise": "gürültü",
  "song": "şarkı",
  "music": "müzik",
  "dream": "rüya/hayal",
  "wish": "dilek/istemek",
  "hope": "umut",
  "fear": "korku",
  "anger": "öfke",
  "joy": "sevinç/neşe",
  "sadness": "üzüntü",
  "pain": "acı",
  "hunger": "açlık",
  "thirst": "susuzluk",
  "sleep": "uyku/uyumak",
  "rest": "dinlenmek",
  "fight": "kavga/savaşmak",
  "battle": "savaş/muharebe",
  "war": "savaş",
  "peace": "barış",
  "friendship": "dostluk",
  "hate": "nefret",
  "trust": "güven",
  "lie": "yalan/yatmak",
  "truth": "gerçek/doğru",
  "secret": "sır/gizli",
  "mystery": "gizemli/sır",
  "danger": "tehlike",
  "adventure": "macera",
  "journey": "yolculuk",
  "quest": "arayış/görev",
  "spell": "büyü/sihir",
  "curse": "lanet",
  "potion": "iksir",
  "treasure": "hazine/define",
  "silver": "gümüş",
  "jewel": "mücevher",
  "crown": "taç",
  "ring": "yüzük",
  "necklace": "kolye",
  "sword": "kılıç",
  "bow": "yay/eğilmek",
  "arrow": "ok",
  "spear": "mızrak",
  "armor": "zırh",
  "shield": "kalkan",
  "knife": "bıçak",
  "rope": "ip/halat",
  "chain": "zincir",
  "key": "anahtar",
  "lock": "kilit/kilitlemek",
  "map": "harita",
  "letter": "mektup/harf",
  "message": "mesaj",
  "mirror": "ayna",
  "candle": "mum",
  "torch": "meşale/el feneri",
  "lantern": "fener",
  "cup": "bardak/fincan",
  "bowl": "kase",
  "plate": "tabak",
  "bread": "ekmek",
  "meat": "et",
  "fish": "balık",
  "fruit": "meyve",
  "apple": "elma",
  "cake": "kek/pasta",
  "soup": "çorba",
  "wine": "şarap",
  "horse": "at",
  "wolf": "kurt",
  "bear": "ayı",
  "lion": "aslan",
  "eagle": "kartal",
  "snake": "yılan",
  "fox": "tilki",
  "deer": "geyik",
  "owl": "baykuş",
  "raven": "kuzgun",
  "king": "kral",
  "queen": "kraliçe",
  "prince": "prens",
  "knight": "şövalye",
  "dragon": "ejderha",
  "giant": "dev",
  "witch": "cadı",
  "wizard": "büyücü",
  "fairy": "peri",
  "elf": "elf/cin",
  "dwarf": "cüce",
  "ghost": "hayalet",
  "monster": "canavar",
  "demon": "iblis",
  "angel": "melek",

  // Common verb forms
  "went": "gitti",
  "gone": "gitmiş",
  "ran": "koştu",
  "jumping": "zıplıyor",
  "shouted": "bağırdı",
  "shout": "bağırmak",
  "whispered": "fısıldadı",
  "whisper": "fısıldamak",
  "smiled": "güldü/güleç",
  "smile": "gülümsemek",
  "cried": "ağladı",
  "cry": "ağlamak",
  "laughed": "güldü",
  "laugh": "gülmek",
  "screamed": "çığlık attı",
  "scream": "çığlık atmak",
  "standing": "ayakta duruyor",
  "stood": "ayakta durdu",
  "sitting": "oturuyor",
  "falling": "düşüyor",
  "rising": "yükseliyor",
  "growing": "büyüyor",
  "told": "söyledi/anlattı",
  "gave": "verdi",
  "took": "aldı",
  "finding": "buluyor",
  "brought": "getirdi",
  "thought": "düşündü",
  "felt": "hissetti",
  "heard": "duydu",
  "spoke": "konuştu",
  "wrote": "yazdı",
  "turned": "döndü",
  "walking": "yürüyor",
  "reaching": "ulaşıyor",
  "pulled": "çekti",
  "pushed": "itti",
  "push": "itmek",
  "pull": "çekmek",
  "carried": "taşıdı",
  "carry": "taşımak",
  "threw": "fırlattı",
  "throw": "atmak/fırlatmak",
  "caught": "yakaladı",
  "catch": "yakalamak",
  "hit": "vurdu",
  "kicked": "tekmeledi",
  "kick": "tekmek/tekmelemek",
  "climbed": "tırmandı",
  "climb": "tırmanmak",
  "swam": "yüzdü",
  "swim": "yüzmek",
  "flew": "uçtu",
  "fly": "uçmak",
  "rode": "bindi",
  "ride": "binmek/sürmek",
  "held": "tuttu",
  "opened": "açtı",
  "closed": "kapattı",
  "close": "kapatmak/yakın",
  "entered": "girdi",
  "enter": "girmek",
  "escaped": "kaçtı",
  "escape": "kaçmak",
  "returned": "döndü",
  "return": "geri dönmek",
  "waited": "bekledi",
  "wait": "beklemek",
  "helped": "yardım etti",
  "help": "yardım etmek",
  "tried": "denedi",
  "needed": "ihtiyaç duydu",
  "called": "aradı/çağırdı",
  "followed": "takip etti",
  "stopped": "durdu",
  "started": "başladı",
  "looked": "baktı",
  "seemed": "göründü",
  "used": "kullandı",
  "left": "ayrıldı/sol",
  "put": "koydu",
  "placed": "yerleştirdi",
  "happened": "oldu",
  "happen": "olmak",
  "continued": "devam etti",
  "continue": "devam etmek",
  "showed": "gösterdi",
  "learned": "öğrendi",
  "remembered": "hatırladı",
  "decided": "karar verdi",
  "decide": "karar vermek",
  "began": "başladı",
  "finished": "bitirdi",
  "finish": "bitirmek",
  "ended": "sona erdi",
  "end": "son/bitirmek",
  "named": "adlandırıldı",
  "name": "isim/ad",
  "died": "öldü",
  "killed": "öldürdü",
  "saved": "kurtardı",
  "broke": "kırdı",
  "break": "kırmak",
  "fixed": "tamir etti",
  "fix": "tamir etmek",
  "won": "kazandı",
  "kept": "tuttu/korudu",
  "met": "tanıştı/buluştu",

  // Adjectives
  "happy": "mutlu/sevinçli",
  "sad": "üzgün/mutsuz",
  "angry": "kızgın/öfkeli",
  "scared": "korkmuş",
  "afraid": "korkmuş/çekingen",
  "worried": "endişeli",
  "surprised": "şaşırmış",
  "excited": "heyecanlı",
  "tired": "yorgun",
  "sick": "hasta",
  "healthy": "sağlıklı",
  "alive": "canlı/yaşayan",
  "dead": "ölü",
  "safe": "güvenli/emniyetli",
  "dangerous": "tehlikeli",
  "brave": "cesur/yiğit",
  "coward": "korkak",
  "clever": "zeki/akıllı",
  "wise": "bilge",
  "foolish": "aptal/akılsız",
  "cruel": "zalim",
  "gentle": "nazik/yumuşak",
  "fierce": "sert/vahşi",
  "quiet": "sessiz",
  "loud": "gürültülü/yüksek sesli",
  "fast": "hızlı",
  "slow": "yavaş",
  "thin": "ince",
  "fat": "şişman/yağlı",
  "tall": "uzun boylu",
  "short": "kısa/kısa boylu",
  "wide": "geniş",
  "narrow": "dar",
  "full": "dolu",
  "clean": "temiz",
  "dirty": "kirli",
  "bright": "parlak/aydınlık",
  "dim": "loş/sönük",
  "silent": "sessiz",
  "noisy": "gürültülü",
  "ancient": "antik/kadim",
  "modern": "modern",
  "strange": "garip/yabancı",
  "familiar": "tanıdık",
  "lonely": "yalnız/ıssız",
  "crowded": "kalabalık",
  "hidden": "gizli/saklı",
  "visible": "görünür/görünebilir",
  "frozen": "donmuş",
  "broken": "kırık",
  "cursed": "lanetlenmiş",
  "enchanted": "büyülenmiş",
  "magical": "sihirli/büyülü",
  "ordinary": "sıradan",
  "special": "özel",
  "precious": "değerli/kıymetli",
  "worthless": "değersiz",

  // Adverbs
  "quickly": "hızlıca/çabucak",
  "quietly": "sessizce",
  "loudly": "yüksek sesle",
  "gently": "nazikçe/yavaşça",
  "finally": "sonunda",
  "already": "zaten/artık",
  "still": "hâlâ/yine de",
  "again": "yeniden/tekrar",
  "away": "uzakta/gitmiş",
  "forward": "ileri/öne",
  "backward": "geri/geriye",
  "together": "birlikte/beraber",
  "alone": "yalnız başına",
  "carefully": "dikkatli bir şekilde",
  "bravely": "cesurca",
  "deeply": "derinden",
  "nearly": "neredeyse/yaklaşık",
  "truly": "gerçekten",
  "really": "gerçekten/çok",
  "perhaps": "belki/muhtemelen",
  "maybe": "belki/olabilir",
  "certainly": "kesinlikle",
  "probably": "muhtemelen",
  "exactly": "tam olarak/kesinlikle",

  // Time and place words
  "morning": "sabah",
  "evening": "akşam",
  "afternoon": "öğleden sonra",
  "midnight": "gece yarısı",
  "dawn": "şafak/gün ağarması",
  "dusk": "alacakaranlık",
  "century": "yüzyıl/asır",
  "decade": "on yıl",
  "moment": "an",
  "minute": "dakika",
  "hour": "saat",
  "week": "hafta",
  "month": "ay",
  "year": "yıl",
  "today": "bugün",
  "yesterday": "dün",
  "tomorrow": "yarın",
  "always": "her zaman",
  "forever": "sonsuza dek",
  "sometimes": "bazen",
  "often": "sık sık",
  "here": "burada",
  "everywhere": "her yerde",
  "nowhere": "hiçbir yerde",
  "somewhere": "bir yerde",
  "nearby": "yakınında",
  "far": "uzak",
  "below": "aşağıda",
  "behind": "arkasında",
  "ahead": "ileride",
  "beside": "yanında",
  "outside": "dışarıda",

  // Body parts
  "head": "kafa/baş",
  "face": "yüz",
  "eye": "göz",
  "eyes": "gözler",
  "nose": "burun",
  "mouth": "ağız",
  "ear": "kulak",
  "ears": "kulaklar",
  "neck": "boyun",
  "shoulder": "omuz",
  "arm": "kol",
  "arms": "kollar",
  "hand": "el",
  "hands": "eller",
  "fingers": "parmaklar",
  "chest": "göğüs",
  "stomach": "mide/karın",
  "leg": "bacak",
  "legs": "bacaklar",
  "knee": "diz",
  "foot": "ayak",
  "feet": "ayaklar",
  "toe": "ayak parmağı",
  "tongue": "dil",
  "teeth": "dişler",
  "tooth": "diş",
  "lip": "dudak",
  "lips": "dudaklar",
  "bone": "kemik",
  "blood": "kan",

  // Common nouns in stories
  "shadow": "gölge",
  "light": "ışık/aydınlık",
  "darkness": "karanlık",
  "silence": "sessizlik",
  "fate": "kader",
  "destiny": "kader",
  "blessing": "bereket/nimet",
  "gift": "hediye/armağan",
  "reward": "ödül/mükafat",
  "punishment": "ceza",
  "lesson": "ders",
  "wisdom": "bilgelik",
  "courage": "cesaret",
  "power": "güç",
  "weakness": "zayıflık",
  "luck": "şans",
  "sign": "işaret",
  "warning": "uyarı",
  "clue": "ipucu",
  "answer": "cevap/yanıt",
  "choice": "seçim",
  "decision": "karar",
  "promise": "söz/vaat",
  "challenge": "zorluk/meydan okuma",
  "enemy": "düşman",
  "friend": "arkadaş",
  "leader": "lider/önderi",
  "follower": "takipçi",
  "stranger": "yabancı",
  "guide": "rehber",
  "guard": "muhafız/koruma",
  "servant": "hizmetkar",
  "master": "usta/efendi",
  "spirit": "ruh/tin",
  "creature": "yaratık/canlı",
  "beast": "canavar/hayvan",
  "hero": "kahraman",
  "heroine": "kadın kahraman",
  "villain": "kötü adam",

  // Additional common words
  "story": "öykü/hikaye",
  "tale": "masal/hikaye",
  "legend": "efsane",
  "myth": "mit/efsane",
  "beginning": "başlangıç",
  "middle": "orta",
  "ending": "son/bitiş",
  "chapter": "bölüm",
  "page": "sayfa",
  "everyone": "herkes",
  "someone": "biri/birisi",
  "anyone": "herhangi biri",
  "nothing": "hiçbir şey",
  "something": "bir şey",
  "everything": "her şey",
  "anything": "her hangi bir şey",
  "either": "her ikisi de/ya da",
  "both": "her ikisi de",
  "neither": "hiçbiri",
  "each": "her biri",
  "every": "her",
  "between": "arasında",
  "among": "arasında",
  "through": "içinden/aracılığıyla",
  "across": "karşı taraf/boyunca",
  "along": "boyunca",
  "past": "geçmişte/yanından",
  "toward": "doğru",
  "beyond": "ötesinde",
  "beneath": "altında",
  "within": "içinde",
  "without": "olmadan",
  "despite": "rağmen",
  "however": "ancak/bununla birlikte",
  "therefore": "bu nedenle",
  "meanwhile": "bu sırada",
  "before": "önce/önde",
  "after": "sonra/ardından",
  "until": "kadar",
  "unless": "aksi halde",
  "although": "rağmen",
  "since": "beri/çünkü",

  // Animals
  "cat": "kedi",
  "dog": "köpek",
  "cow": "inek",
  "pig": "domuz",
  "goat": "keçi",
  "duck": "ördek",
  "chicken": "tavuk",
  "rooster": "horoz",
  "goose": "kaz",
  "mouse": "fare",
  "rat": "sıçan",
  "frog": "kurbağa",
  "turtle": "kaplumbağa",
  "crow": "karga",
  "sparrow": "serçe",
  "swan": "kuğu",
  "tiger": "kaplan",
  "elephant": "fil",
  "monkey": "maymun",
  "peacock": "tavus kuşu",
  "butterfly": "kelebek",
  "bee": "arı",
  "ant": "karınca",
  "spider": "örümcek",
  "worm": "solucan",

  // Colors
  "red": "kırmızı",
  "green": "yeşil",
  "yellow": "sarı",
  "black": "siyah",
  "brown": "kahverengi",
  "orange": "turuncu",
  "pink": "pembe",
  "gray": "gri",
  "golden": "altın rengi",

  // Numbers and quantities
  "zero": "sıfır",
  "four": "dört",
  "five": "beş",
  "six": "altı",
  "eight": "sekiz",
  "nine": "dokuz",
  "ten": "on",
  "twenty": "yirmi",
  "fifty": "elli",
  "thousand": "bin",
  "million": "milyon",
  "few": "az/birkaç",
  "many": "çok/pek çok",
  "much": "çok (miktar)",
  "enough": "yeterli",
  "several": "birkaç/çeşitli",
  "whole": "bütün/tüm",
  "half": "yarım",
  "double": "çift/iki katı",
  "single": "tek/tekli",
  "pair": "çift/ikili"
};

// Generates correct types and alignments dynamically from raw definitions
export const INITIAL_BOOKS: Book[] = ALL_RAW_STORIES.map((story) => {
  const chapters = [
    {
      id: `${story.id}_chap1`,
      title: '',
      paragraphs: story.en.map((enText, pIdx) => {
        const trText = story.tr[pIdx] || enText;
        
        // Populate interactive lookup words
        const paragraphWords: { en: string; tr: string }[] = [];
        
        // Clean words and match with dicts
        const wordsInText = enText.split(/\s+/);
        wordsInText.forEach(rawW => {
          const cleanW = rawW.replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?"'’“”‘’\[\]{}<>|\\+]/g, "").trim().toLowerCase();
          if (!cleanW) return;
          
          const tr = story.words[cleanW] || GLOBAL_DICTIONARY[cleanW];
          if (tr) {
            if (!paragraphWords.some(w => w.en.toLowerCase() === cleanW)) {
              paragraphWords.push({ en: cleanW, tr });
            }
          }
        });

        return {
          id: `${story.id}_p${pIdx + 1}`,
          textEn: enText,
          textTr: trText,
          words: paragraphWords
        };
      })
    }
  ];

  const totalWords = story.en.reduce((sum, p) => sum + p.split(/\s+/).filter(Boolean).length, 0);
  const calculatedTotalPages = Math.max(1, Math.round(totalWords / 125.0));

  return {
    id: story.id,
    title: story.title,
    author: story.author === 'Antigravity' ? '' : (story.author || ''),
    level: story.level,
    levelName: LEVEL_NAMES[story.level] || `${story.level} Seviyesi`,
    coverUrl: story.coverUrl,
    percentageCompleted: 0,
    pagesLeft: calculatedTotalPages,
    totalPages: calculatedTotalPages,
    currentPage: 0,
    statsWords: totalWords,
    statsTime: `${Math.max(1, Math.ceil(totalWords / 45))}dk`,
    chapters,
    titleTr: STORY_TITLE_TRANSLATIONS[story.id] || '',
    coverPosition: (story as any).coverPosition || 'center 28%'
  };
});

export const INITIAL_VOCABULARY: VocabularyWord[] = [];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    word: 'Perseverance',
    level: 'B2 Seviyesi',
    options: ['Kararsızlık', 'Azim / Sebat', 'Tembellik', 'Zayıflık'],
    correctIndex: 1,
    hint: 'Sözcük, zor durumlarda vazgeçmeme, sabırla devam etmeyi simgeler.',
    explanation: '"Perseverance" kelimesi zorluklara karşı durup azim ve sebat göstermek anlamına gelir.'
  },
  {
    id: 'q2',
    word: 'Eloquent',
    level: 'C1 Seviyesi',
    options: ['Güzel ve etkili konuşan', 'Kaba / Patavatsız', 'Sessiz / Çekingen', 'Kekeme'],
    correctIndex: 0,
    hint: 'Bir hatibin etkileyici, akıcı ve ikna edici konuşması durumudur.',
    explanation: '"Eloquent" fasih, belagatli ve güzel/etkili konuşan demektir.'
  },
  {
    id: 'q3',
    word: 'Vulnerable',
    level: 'B2 Seviyesi',
    options: ['Kırılmaz / Güçlü', 'Hassas / Kırılgan', 'Umutsuz', 'Diktatör'],
    correctIndex: 1,
    hint: 'Dış etkenlere karşı kendini koruyamayan, kolayca zarar görebilen yapılar içindir.',
    explanation: '"Vulnerable" fiziksel veya psikolojik olarak incinmeye açık olan "hassas / kırılgan" demektir.'
  },
  {
    id: 'q4',
    word: 'Gorgeous',
    level: 'B1 Seviyesi',
    options: ['Sıradan', 'Çirkin', 'Harika / Muazzam', 'Tehlikeli'],
    correctIndex: 2,
    hint: 'Çok güzel, göz alıcı şeyler tasvir edilirken tercih edilir.',
    explanation: '"Gorgeous" kelimesi göz kamaştırıcı güzellikteki harika, muazzam nesneler veya kişiler içindir.'
  },
  {
    id: 'q5',
    word: 'Exempt',
    level: 'C1 Seviyesi',
    options: ['Muaf tutulmuş', 'Kabul edilmiş', 'Zorunlu kılınmış', 'Cezalandırılmış'],
    correctIndex: 0,
    hint: 'Kişinin birtakım vergilerden veya kurallardan hariç tutulması durumudur.',
    explanation: '"Exempt" bir kural veya yükümlülükten ötürü hariç ya da muaf tutulmak demektir.'
  }
];

export const LEADERBOARD_DATA: LeaderboardUser[] = [
  { id: '1', name: 'Barış Demir', xp: 2840, rank: 1, avatarUrl: AVATAR_OPTIONS[7] }, // Mavi Kapüşonlu Çocuk
  { id: '2', name: 'Zeynep Kaya', xp: 2410, rank: 2, avatarUrl: AVATAR_OPTIONS[4] }, // Ağaç Altında Okuyan Kız
  { id: '4', name: 'Can Yılmaz', xp: 1850, rank: 3, avatarUrl: AVATAR_OPTIONS[11] }, // Ceketli Sincap
  { id: '5', name: 'Merve Çelik', xp: 1540, rank: 4, avatarUrl: AVATAR_OPTIONS[13] }, // Kahveli Genç Okuyucu
  { id: '3', name: 'Selim Kaya', xp: 0, rank: 5, isCurrentUser: true, avatarUrl: AVATAR_OPTIONS[0] } // Gözlüklü Kitap Kurdu Çocuk
];

export const INITIAL_BADGES: Badge[] = [
  { id: 'b6', title: 'İlk Adım', description: 'İlk hikayeni başarıyla tamamla.', iconName: 'Zap', unlocked: false },
  { id: 'b11', title: 'Okumaya Alışmak', description: 'Toplam 10 dakika okuma süresine ulaş.', iconName: 'Clock', unlocked: false },
  { id: 'b7', title: 'Kelime Meraklısı', description: 'Kelime haznesine 20 yeni kelime kaydet.', iconName: 'BadgeCheck', unlocked: false },
  { id: 'b1', title: 'Kitap Kurdu', description: 'En az 5 farklı İngilizce hikaye oku.', iconName: 'BookOpen', unlocked: false },
  { id: 'b14', title: 'Çelik İrade', description: 'Günlük hedefini üst üste 5 gün tamamla.', iconName: 'Flame', unlocked: false },
  { id: 'b12', title: 'Kelime Koleksiyoneri', description: 'Kelime haznesine 50 yeni kelime kaydet.', iconName: 'Award', unlocked: false },
  { id: 'b13', title: 'Dil Kaşifi', description: '3 farklı zorluk seviyesinden hikayeler bitir.', iconName: 'Volume2', unlocked: false },
  { id: 'b9', title: 'Kütüphaneci', description: 'En az 10 farklı hikayeye başla.', iconName: 'Library', unlocked: false },
  { id: 'b8', title: 'Zaman Bükücü', description: 'Toplam 100 dakika okuma süresine ulaş.', iconName: 'Clock', unlocked: false },
  { id: 'b4', title: 'Kusursuz Akıl', description: 'Bir kelime quizini can kaybetmeden bitir.', iconName: 'Sparkles', unlocked: false },
  { id: 'b3', title: 'Kelime Avcısı', description: 'Kelime haznesine 100 yeni kelime kaydet.', iconName: 'Award', unlocked: false },
  { id: 'b2', title: 'Azimli Sebat', description: 'Günlük hedefini üst üste 15 gün tamamla.', iconName: 'Flame', unlocked: false },
  { id: 'b10', title: 'Bilge Gezgin', description: 'C1 seviyesinde en az bir hikaye bitir.', iconName: 'Trophy', unlocked: false },
  { id: 'b15', title: 'Efsanevi Okur', description: 'Toplam 500 dakika okuma süresine ulaş.', iconName: 'Trophy', unlocked: false },
  { id: 'b5', title: 'Premium Üye', description: 'Sınırsız can ve premium ayrıcalıkları aktif et.', iconName: 'Crown', unlocked: false },
  { id: 'b16', title: 'Eşleme Çırağı', description: 'İlk eş bulma oyununu başarıyla tamamla.', iconName: 'Puzzle', unlocked: false },
  { id: 'b17', title: 'Eşleme Ustası', description: '5 kez eş bulma oyununu başarıyla tamamla.', iconName: 'Trophy', unlocked: false },
  { id: 'b18', title: 'Kelime Dedektifi', description: 'İlk boşluk doldurma oyununu başarıyla tamamla.', iconName: 'Search', unlocked: false },
  { id: 'b19', title: 'Boşluk Bükücü', description: '5 kez boşluk doldurma oyununu başarıyla tamamla.', iconName: 'Sparkles', unlocked: false }
];

export const ANALYTICS_DATA = [
  { day: 'Pzt', learnedWords: 0, readMins: 0 },
  { day: 'Sal', learnedWords: 0, readMins: 0 },
  { day: 'Çar', learnedWords: 0, readMins: 0 },
  { day: 'Per', learnedWords: 0, readMins: 0 },
  { day: 'Cum', learnedWords: 0, readMins: 0 },
  { day: 'Cmt', learnedWords: 0, readMins: 0 },
  { day: 'Paz', learnedWords: 0, readMins: 0 }
];

const getLibraryUniqueWordsCount = (): number => {
  const uniqueWordsSet = new Set<string>();
  INITIAL_BOOKS.forEach(book => {
    if (book.chapters) {
      book.chapters.forEach(chap => {
        if (chap.paragraphs) {
          chap.paragraphs.forEach(p => {
            if (p.words) {
              p.words.forEach(w => {
                const clean = w.en.trim().toLowerCase();
                if (clean) {
                  uniqueWordsSet.add(clean);
                }
              });
            }
          });
        }
      });
    }
  });
  return uniqueWordsSet.size;
};

export const LIBRARY_UNIQUE_WORDS_COUNT = getLibraryUniqueWordsCount();

